classdef UIViewAnalyze < CellVision3D.UIView
    % choose analysis to run
    
    properties
        addanalysis_button_handle
        cell_analysis_handles
    end
    
    methods
        
        % constructor
        function obj=UIViewAnalyze(varargin)
            obj@CellVision3D.UIView(varargin{:});
            channel_y0=0.95;
            channel_dy=0.06;
            channel_dx=1/4;
            margin=0.01;

            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','Please add types of analysis',...
                'Units','normalized','Position',[margin channel_y0+margin-0.01 2/3-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            
            % add filter button
            obj.addanalysis_button_handle=...
                uicontrol('Parent',obj.main_panel,...
                'Style','pushbutton',...
                'String','Add Analysis',...
                'Units','normalized','Position',[margin channel_y0-channel_dy+margin .2-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left',...
                'Callback',@addAnalysis);
            
            %
%             obj.printHelpMessage;
            
            % filter specs text
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','Analysis Type',...
                'Units','normalized','Position',...
                [margin channel_y0-channel_dy*2+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','Input Channel 1',...
                'Units','normalized','Position',...
                [1/4+margin channel_y0-channel_dy*2+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','Input Channel 2',...
                'Units','normalized','Position',...
                [2/4+margin channel_y0-channel_dy*2+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','Input Channel 3',...
                'Units','normalized','Position',...
                [3/4+margin channel_y0-channel_dy*2+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            % movie lables
            try
                channeltypes={obj.data.movie.getChannel.type};
                channellabels={obj.data.movie.getChannel.label};
            catch
                channeltypes=[];
                channellabels=[];
            end
            
            % analysis types
            [analysismethods,analysisdescription,inputformats]=CellVision3D.CellAnalyzer.getCellAnalysisMethods;
            numfilters=0;
            analysistypes=analysismethods;
            addAnalysis([],[])
            
            % add details of input
            function addAnalysis(hobj,eventdata)
                numfilters=numfilters+1;
                currentfilterid=numfilters;
                % filter specs text
                obj.cell_analysis_handles(numfilters,1)=uicontrol('Parent',obj.main_panel,...
                    'Style','popupmenu',...
                    'String',analysisdescription,'Value',1,...
                    'Units','normalized','Position',...
                    [margin channel_y0-channel_dy*(2+numfilters)+margin 1/4-margin channel_dy-2*margin],...
                    'FontSize',14,'HorizontalAlignment','left',...
                    'Callback',@(hobj,eventdata)addDetail(hobj,eventdata,currentfilterid));
            end
            
            % set filter details
            function addDetail(hobj,eventdata,ifilter)
                % chosen filter type
                index = get(hobj,'Value');
                analysistype = analysistypes(index);
                
                % clear previous detail
                try
                    delete(obj.cell_analysis_handles(ifilter,2));
                catch
                end
                try
                    delete(obj.cell_analysis_handles(ifilter,3));
                catch
                end
                try
                    delete(obj.cell_analysis_handles(ifilter,4));
                catch
                end
                
                if ~strcmp(analysistype,'none')
                    % available labels
                    inputformat=inputformats{index};
                    % set up inputs
                   for iinput=1:length(inputformat)
                       % availabe types for this kind of inputformat
                       availabletypes=channellabels(cellfun(...
                           @(x)~isempty(strfind(x,inputformat{iinput})),...
                           channeltypes));
                       if isempty(availabletypes)
                        obj.cell_analysis_handles(ifilter,iinput+1)=uicontrol('Parent',obj.main_panel,...
                            'Style','text',...
                            'String','Not Available',...
                            'Units','normalized','Position',...
                            [margin+iinput*channel_dx channel_y0-channel_dy*(2+ifilter)+margin 1/4-margin channel_dy-2*margin],...
                            'FontSize',14,'HorizontalAlignment','left');
                       else
                       % create selector
                        obj.cell_analysis_handles(ifilter,iinput+1)=uicontrol('Parent',obj.main_panel,...
                            'Style','popupmenu',...
                            'String',availabletypes,'Value',1,...
                            'Units','normalized','Position',...
                            [margin+iinput*channel_dx channel_y0-channel_dy*(2+ifilter)+margin 1/4-margin channel_dy-2*margin],...
                            'FontSize',14,'HorizontalAlignment','left');
                       end
                   end
                end
            end
            
        end
        
        
        
    end
    
end

