function [ vols ] = getVolume( obj )
% get volume of the contour
% currently it assumes all the face indices is aligned
% it may not be true for general cases, however meshes generated by
% spherical method is always true
% this problem can be fixed by the function AlignFaceDirection, which is
% currently not integrated
% Yao Zhao 5/17/2016

numframes = obj.numframes;
vols=zeros(numframes,1);
for iframe=1:length(numframes)
    vertices = obj.vertices{iframe};
    faces = obj.faces{iframe};
    for iface=1:size(faces,1)
        p1=vertices(faces(iface,1),:);
        p2=vertices(faces(iface,2),:);
        p3=vertices(faces(iface,3),:);
        vols(iframe)=vols(iframe)+1/6*(cross(p2-p1,p3-p2)*p2');
    end
end
vols = abs(vols);
% % initialize
% vols=zeros(obj.numpatches,1);
% for ipatch=1:obj.numpatches
%     faces=obj.faces(obj.facespid==ipatch,:);
%     numfaces=size(faces,1);
%     for iface=1:numfaces
%         p1=pts(faces(iface,1),:);
%         p2=pts(faces(iface,2),:);
%         p3=pts(faces(iface,3),:);
%         vols(ipatch)=vols(ipatch)+1/6*(cross(p2-p1,p3-p2)*p2');
%     end
%     if obj.isoutward(ipatch)==0
%         vols(ipatch)=vols(ipatch)*-1;
%     end
% end

end

