classdef UIViewCell< CellVision3D.UIView
    % uiview initialize the movies
    % Yao Zhao 12/12/2015
    
    
    properties (Constant)
    end
    
    properties
        % selector for cell filter methods
        cell_methods_selector_handle
        % add filter button
        addfilter_button_handle
        % filter handles
        cell_filters_handles
    end
    
    methods
        % constructor
        function obj=UIViewCell(varargin)
            obj@CellVision3D.UIView(varargin{:});
            channel_y0=0.9;
            channel_dy=0.06;
            margin=0.01;
            % cell constructor types
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','Please choose how to construct the cells from multiple channels',...
                'Units','normalized','Position',[margin channel_y0+margin-0.01 2/3-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            [constructionmethods,descriptions]=CellVision3D.CellConstructor.getCellConstructionMethods;
            obj.cell_methods_selector_handle=uicontrol('Parent',obj.main_panel,...
                'Style','popupmenu',...
                'String',descriptions,'value',1,...
                'Units','normalized','Position',[margin channel_y0-channel_dy+margin 2/3-2*margin channel_dy-2*margin],...
                'FontSize',20,'CallBack',@(hobj,eventdata)1);
            % add filter button
            obj.addfilter_button_handle=...
                uicontrol('Parent',obj.main_panel,...
                'Style','pushbutton',...
                'String','Add Filter',...
                'Units','normalized','Position',[margin channel_y0-channel_dy*2+margin .2-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left',...
                'Callback',@addFilter);
            
            %
            obj.printHelpMessage;
            
            % filter specs text
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','FilterType',...
                'Units','normalized','Position',...
                [margin channel_y0-channel_dy*3+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','ChannelLabel',...
                'Units','normalized','Position',...
                [1/4+margin channel_y0-channel_dy*3+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','MinValue',...
                'Units','normalized','Position',...
                [2/4+margin channel_y0-channel_dy*3+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','MaxValue',...
                'Units','normalized','Position',...
                [3/4+margin channel_y0-channel_dy*3+margin 1/4-margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            % movie lables
            try
                types={obj.data.movie.getChannel.type};
                labels={obj.data.movie.getChannel.label};
            catch
                types=[];
                labels=[];
            end
            % filter types
            numfilters=0;
            filtertypes=sort([properties(CellVision3D.CellFilter),'none']);
            addFilter([],[])
            
            % add filter
            function addFilter(hobj,eventdata)
                numfilters=numfilters+1;
                currentfilterid=numfilters;
                % filter specs text
                obj.cell_filters_handles(numfilters,1)=uicontrol('Parent',obj.main_panel,...
                    'Style','popupmenu',...
                    'String',filtertypes,'Value',length(filtertypes),...
                    'Units','normalized','Position',...
                    [margin channel_y0-channel_dy*(3+numfilters)+margin 1/4-margin channel_dy-2*margin],...
                    'FontSize',14,'HorizontalAlignment','left',...
                    'Callback',@(hobj,eventdata)addFilterDetail(hobj,eventdata,currentfilterid));
            end
            % set filter details
            function addFilterDetail(hobj,eventdata,ifilter)
                % chosen filter type
                filtertype = filtertypes{get(hobj,'Value')};
                
                % clear previous
                try
                    delete(obj.cell_filters_handles(ifilter,2));
                catch
                end
                try
                    delete(obj.cell_filters_handles(ifilter,3));
                catch
                end
                try
                    delete(obj.cell_filters_handles(ifilter,4));
                catch
                end
                
                
                if ~strcmp(filtertype,'none')
                    % available labels
                    token=strfind(filtertype,'_');
                    type=filtertype(1:token(1)-1);
                    typelabels=labels(strcmp(types,type));
                    % set up inputs
                    if ~isempty(typelabels)
                        obj.cell_filters_handles(ifilter,2)=uicontrol('Parent',obj.main_panel,...
                            'Style','popupmenu',...
                            'String',typelabels,'Value',1,...
                            'Units','normalized','Position',...
                            [1/4+margin channel_y0-channel_dy*(3+ifilter)+margin 1/4-margin channel_dy-2*margin],...
                            'FontSize',14,'HorizontalAlignment','left');
                        
                        obj.cell_filters_handles(ifilter,3)=uicontrol('Parent',obj.main_panel,...
                            'Style','edit',...
                            'String','-inf',...
                            'Units','normalized','Position',...
                            [2/4+margin channel_y0-channel_dy*(3+ifilter)+margin 1/4-margin channel_dy-2*margin],...
                            'FontSize',14,'HorizontalAlignment','left');
                        
                        obj.cell_filters_handles(ifilter,4)=uicontrol('Parent',obj.main_panel,...
                            'Style','edit',...
                            'String','inf',...
                            'Units','normalized','Position',...
                            [3/4+margin channel_y0-channel_dy*(3+ifilter)+margin 1/4-margin channel_dy-2*margin],...
                            'FontSize',14,'HorizontalAlignment','left');
                    end
                else
                    
                end
            end
            
        end
        
        
    end
    
end

