classdef UIViewLoadMovie < CellVision3D.UIView
    % uiview load movie
    % Yao Zhao 12/12/2015
    
    properties (Constant)
    end
    properties
        movie_filename_text_handle
        movie_filename_button_handle
        number_channel_selector_handle
        channel_labels_edit_handles
        channel_labels_text_handles
        channel_types_selector_handles
        channel_types_text_handles
    end
    
    methods
        % constructor
        function obj=UIViewLoadMovie(varargin)
            obj@CellVision3D.UIView(varargin{:});
            channel_y0=0.8;
            channel_dy=0.06;
            margin=0.01;
            % moviepath
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','Please enter the file name here or click the search button on the right',...
                'Units','normalized','Position',[margin channel_y0+channel_dy*2+margin-0.01 .8-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            obj.movie_filename_text_handle=...
                uicontrol('Parent',obj.main_panel,...
                'Style','edit',...
                'String','sample_image.dv',...
                'Units','normalized','Position',[margin channel_y0+channel_dy+margin .8-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');     
            obj.movie_filename_button_handle=...
                uicontrol('Parent',obj.main_panel,...
                'Style','pushbutton',...
                'String','Search',...
                'Units','normalized','Position',[.8+margin channel_y0+channel_dy+margin .2-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left',...
                'Callback',@searchFile);
            
            % number of channel selector
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','number of channels',...
                'Units','normalized','Position',[margin channel_y0+margin-0.01 1/3-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            obj.number_channel_selector_handle=uicontrol('Parent',obj.main_panel,...
                'Style','popupmenu',...
                'String',{'1','2','3','4'},'value',1,...
                'Units','normalized','Position',[margin channel_y0-channel_dy+margin 1/3-2*margin channel_dy-2*margin],...
                'FontSize',20,'CallBack',@(hobj,eventdata)setChannels(hobj,eventdata,obj));
            
            % set inital channels
            setChannels(obj.number_channel_selector_handle,[],obj);
            
            % print help message
            obj.printHelpMessage()
            

            
            % set channels
            function setChannels(hobj,eventdata,obj)
                for i=1:length(obj.channel_labels_edit_handles)
                    if ishandle(obj.channel_labels_edit_handles(i))
                    delete(obj.channel_labels_edit_handles(i));
                    delete(obj.channel_labels_text_handles(i));
                    delete(obj.channel_types_selector_handles(i));
                    delete(obj.channel_types_text_handles(i));
                    end
                end
                numchannels=hobj.Value;
                for ichannel=1:numchannels
                    % selector label
                    obj.channel_types_text_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','text',...
                        'String',['Channel ',num2str(ichannel),' Type'],...
                        'Units','normalized',...
                        'Position',[1/3+margin channel_y0-(ichannel-1)*2*channel_dy+margin-0.01 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20,'HorizontalAlignment','left');
                    % type selector
                    % possible channels
                    [~,~,channelsdesc] = CellVision3D.Channel.getChannelTypes();
                    obj.channel_types_selector_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','popupmenu',...
                        'String',channelsdesc,'value',1,...
                        'Units','normalized',...
                        'Position',[1/3+margin channel_y0-channel_dy-(ichannel-1)*2*channel_dy+margin 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20);
                    % text input label
                    obj.channel_labels_text_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','text',...
                        'String',['Channel ',num2str(ichannel),' Label'],...
                        'Units','normalized',...
                        'Position',[2/3+margin channel_y0-(ichannel-1)*2*channel_dy+margin-0.01 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20,'HorizontalAlignment','left');
                    % text input
                    obj.channel_labels_edit_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','edit',...
                        'String',['Channel',num2str(ichannel)],...
                        'Units','normalized',...
                        'Position',[2/3+margin channel_y0-channel_dy-(ichannel-1)*2*channel_dy+margin 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20,'HorizontalAlignment','left');
                end
            end
            
            % search for file
            function searchFile(hobj,event)
                [FileName,PathName,FilterIndex] = uigetfile('*','Choose the movie file to be analyzed');
                if ~isempty(FileName)
                    obj.movie_filename_text_handle.set('String',fullfile(PathName,FileName));
                end
            end
        end
        
        
    end
    
end

