classdef UIViewLoadMovie < CellVision3D.UIView
    % uiview load movie
    % Yao Zhao 12/12/2015
    
    properties (Constant)
        channel_options={'none','BrightfieldContour3D','FluorescentMembrane3D',...
            'FluorescentParticle3D'};
    end
    properties
        movie_filename_text_handle
        movie_filename_button_handle
        number_channel_selector_handle
        channel_labels_edit_handles
        channel_labels_text_handles
        channel_types_selector_handles
        channel_types_text_handles
    end
    
    methods
        % constructor
        function obj=UIViewLoadMovie()
            obj@CellVision3D.UIView();
            channel_y0=0.8;
            channel_dy=0.06;
            margin=0.01;
            % moviepath
            % number of channel selector
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','movie file name',...
                'Units','normalized','Position',[margin channel_y0+channel_dy*2+margin-0.01 .8-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            obj.movie_filename_text_handle=...
                uicontrol('Parent',obj.main_panel,...
                'Style','edit',...
                'String','enter file name here or press search button',...
                'Units','normalized','Position',[margin channel_y0+channel_dy+margin .8-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');     
            obj.movie_filename_button_handle=...
                uicontrol('Parent',obj.main_panel,...
                'Style','pushbutton',...
                'String','Search',...
                'Units','normalized','Position',[.8+margin channel_y0+channel_dy+margin .2-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left',...
                'Callback',@searchFile);
            
            % number of channel selector
            uicontrol('Parent',obj.main_panel,...
                'Style','text',...
                'String','number of channels',...
                'Units','normalized','Position',[margin channel_y0+margin-0.01 1/3-2*margin channel_dy-2*margin],...
                'FontSize',20,'HorizontalAlignment','left');
            obj.number_channel_selector_handle=uicontrol('Parent',obj.main_panel,...
                'Style','popupmenu',...
                'String',{'1','2','3','4'},'value',1,...
                'Units','normalized','Position',[margin channel_y0-channel_dy+margin 1/3-2*margin channel_dy-2*margin],...
                'FontSize',20,'CallBack',@(hobj,eventdata)setChannels(hobj,eventdata,obj));
            
            % set inital channels
            setChannels(obj.number_channel_selector_handle,[],obj);
           
            obj.print('current step ----------------------------');
            obj.print('');
            obj.print('Please enter or select the movie to be analyzed');
            obj.print('');
            obj.print('Please select number of channels of the movie file');
            obj.print('');
            obj.print('Please select the type of each channel');
            obj.print('Only three types are currently enabled');
            obj.print('');
            obj.print('BrightfieldContour3D: cell contours from the brightfield image');
            obj.print('');
            obj.print('FluorescentMembrane3D: membrane contours from the fluorescent image');
            obj.print('');
            obj.print('FluorescentParticle3D: particle localizations from the fluorescent image');
            obj.print('');
            obj.print('Please enter a label of each channel for your reference');
            obj.print('');
            obj.print('Next step --------------------------------');
            obj.print('');
            obj.print('Load Movie and Initialize movie');
            
            % set channels
            function setChannels(hobj,eventdata,obj)
                for i=1:length(obj.channel_labels_edit_handles)
                    if ishandle(obj.channel_labels_edit_handles(i))
                    delete(obj.channel_labels_edit_handles(i));
                    delete(obj.channel_labels_text_handles(i));
                    delete(obj.channel_types_selector_handles(i));
                    delete(obj.channel_types_text_handles(i));
                    end
                end
                numchannels=hobj.Value;
                for ichannel=1:numchannels
                    % selector label
                    obj.channel_types_text_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','text',...
                        'String',['Channel ',num2str(ichannel),' Type'],...
                        'Units','normalized',...
                        'Position',[1/3+margin channel_y0-(ichannel-1)*2*channel_dy+margin-0.01 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20,'HorizontalAlignment','left');
                    % type selector
                    obj.channel_types_selector_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','popupmenu',...
                        'String',obj.channel_options,'value',1,...
                        'Units','normalized',...
                        'Position',[1/3+margin channel_y0-channel_dy-(ichannel-1)*2*channel_dy+margin 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20);
                    % text input label
                    obj.channel_labels_text_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','text',...
                        'String',['Channel ',num2str(ichannel),' Label'],...
                        'Units','normalized',...
                        'Position',[2/3+margin channel_y0-(ichannel-1)*2*channel_dy+margin-0.01 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20,'HorizontalAlignment','left');
                    % text input
                    obj.channel_labels_edit_handles(ichannel)=...
                        uicontrol('Parent',obj.main_panel,...
                        'Style','edit',...
                        'String',['Channel',num2str(ichannel)],...
                        'Units','normalized',...
                        'Position',[2/3+margin channel_y0-channel_dy-(ichannel-1)*2*channel_dy+margin 1/3-2*margin channel_dy-2*margin],...
                        'FontSize',20,'HorizontalAlignment','left');
                end
            end
            
            % search for file
            function searchFile(hobj,event)
                [FileName,PathName,FilterIndex] = uigetfile('*','Choose the movie file to be analyzed');
                if ~isempty(FileName)
                    obj.movie_filename_text_handle.set('String',fullfile(PathName,FileName));
                end
            end
        end
        
                
        % go next
        function varargout=next(obj,varargin)
            % create movie
            movie=CellVision3D.Movie(obj.movie_filename_text_handle.get('String'));
            % number of channels
            numchannels=obj.number_channel_selector_handle.get('Value');
            str=[];
            for ichannel=1:numchannels
                if ichannel>1
                    str=[str,','];
                end
                str=[str,'''',obj.channel_options{...
                    get(obj.channel_types_selector_handles(ichannel),'Value')},...
                    ''',''',get(obj.channel_labels_edit_handles(ichannel),'String'),...
                    ''''];
            end
            % setup channels
            eval(['movie.setChannels(',str,');']);
            % output
            varargout{1}=movie;
        end
    end
    
end

